name: Build Plugins

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
      
    - name: Build plugins
      run: ./gradlew assembleRelease
      
    - name: Upload APKs
      uses: actions/upload-artifact@v3
      with:
        name: plugins
        path: "*/build/outputs/apk/release/*.apk"
        
    - name: Create Release
      if: github.ref == 'refs/heads/main'
      uses: softprops/action-gh-release@v1
      with:
        tag_name: v${{ github.run_number }}
        files: "*/build/outputs/apk/release/*.apk"
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
